### PR TITLE
Add Google I/O Extended 2017 Embedded Widget

### PR DESCRIPTION
**Pull request by mariobodemann**
As a preparation for the I/O extended session we are going to host somewhere, let us enthuse our audience with a teaser ...

[FAQ](https://events.google.com/io/widget/)

### CODE REVIEW

**Comment by cketti** [comment]
An `iframe`? You are the devil!

**Comment by akarsh** [comment]
Is it bad to use iframe ?
I did not find anything related to cons in the [w3c schools](https://www.w3schools.com/tags/tag_iframe.asp); Is there any specific website that shows pros & cons of using HTML tags ?

**Comment by alosdev** [comment]
why not, even if it is an iframe

**Comment by alosdev** [comment]
btw. any screenshot?

**Comment by mariobodemann** [comment]
I think it is too late ... Closing it...

**Pull request closed without merging**
